### ISSUE TITLE
Wiki is not editable...

### ISSUE THREAD

**Issue by dshadoff** [charlesmacd/PC-Engine-Information#1]
I was interested in contributing to the wiki, but it doesn't seems to be publicly editable.
Do you have a policy on how to contribute ?

**Comment by charlesmacd** [comment]
Hey good to hear from you! Sorry for the delay, I've sent you an invite to make you a collaborator which should give you Wiki access. 

No real policy about the Wiki other than all content should preferably be original research, and if it isn't sources have to be cited. I'll add some boilerplate to the Wiki about that next.

If there's any difficulties feel free to e-mail me: http://techno-junk.org/contact.php
